from typing import Callable, Dict, Iterable
from abc import ABC, abstractmethod
import pyparsing as pp
from pyparsing import pyparsing_common as ppc
import json

def extract_and_parse_jsons(text):
    def make_keyword(kwd_str, kwd_value):
        return pp.Keyword(kwd_str).setParseAction(pp.replaceWith(kwd_value))

    if not hasattr(extract_and_parse_jsons, "jsonDoc"):
        # set to False to return ParseResults
        RETURN_PYTHON_COLLECTIONS = True

        TRUE = make_keyword("true", True)
        FALSE = make_keyword("false", False)
        NULL = make_keyword("null", None)

        LBRACK, RBRACK, LBRACE, RBRACE, COLON = map(pp.Suppress, "[]{}:")

        jsonString = pp.dblQuotedString().setParseAction(pp.removeQuotes)
        jsonNumber = ppc.number().setName("jsonNumber")

        jsonObject = pp.Forward().setName("jsonObject")
        jsonValue = pp.Forward().setName("jsonValue")

        jsonElements = pp.delimitedList(jsonValue).setName(None)

        jsonArray = pp.Group(
            LBRACK + pp.Optional(jsonElements) + RBRACK, aslist=RETURN_PYTHON_COLLECTIONS
        ).setName("jsonArray")

        jsonValue << (jsonString | jsonNumber | jsonObject | jsonArray | TRUE | FALSE | NULL)

        memberDef = pp.Group(
            jsonString + COLON + jsonValue, aslist=RETURN_PYTHON_COLLECTIONS
        ).setName("jsonMember")

        jsonMembers = pp.delimitedList(memberDef).setName(None)
        jsonObject << pp.Dict(
            LBRACE + pp.Optional(jsonMembers) + RBRACE, asdict=RETURN_PYTHON_COLLECTIONS
        )

        jsonComment = pp.cppStyleComment
        jsonObject.ignore(jsonComment)
        jsonDoc = jsonObject | jsonArray
        extract_and_parse_jsons.jsonDoc = jsonDoc
    for _, l, r in extract_and_parse_jsons.jsonDoc.scanString(text):
        json_string = text[l:r]
        try:
            parsed_data = json.loads(json_string)

            if isinstance(parsed_data, list):
                for item in parsed_data:
                    yield item
            else:
                yield parsed_data
        except json.JSONDecodeError as e:
            print(f"JSON decoding error: {e}")
        except Exception as e:
            print(f"An error occurred: {e}")

class DataFilter(ABC):
    def __init__(self, fail_callback: Callable[[Dict[str, str]], None] = None):
        self.fail_callback = fail_callback
    
    def preprocess(self, data: Iterable[Dict[str, str]])->Iterable[Dict[str, str]]:
        # you can create new data from the original data here.
        # not just filter the data.
        return data
    
    @abstractmethod
    def validate(self, data: Dict[str, str])->bool:
        # filter the data generated by preprocess.
        raise NotImplementedError
    
    def filter(self, data: Iterable[Dict[str, str]])->Iterable[Dict[str, str]]:
        for d in self.preprocess(data):
            if self.validate(d):
                yield d
            else:
                if self.fail_callback:
                    self.fail_callback(d)

class JsonExtractor(DataFilter):
    def preprocess(self, data: Iterable[Dict[str, str]]) -> Iterable[Dict[str, str]]:        
        for d in data:            
            # if d["finish_reason"] == "stop":                                    
            for item in extract_and_parse_jsons(d["text"]):                
                yield item
            else:
                if self.fail_callback:
                    self.fail_callback(d)
    
    def validate(self, data: Dict[str, str]) -> bool:        
        return True